# Site vars
title: quittit!
email: max.loiacono@protonmail.com
description: Resources to aide in quitting reddit, and other addicting sites

baseurl: "" # the subpath of your site, e.g. /blog
hard_url: "quittit.itsmaxymoo.com"

author:  itsmaxymoo
author_full: Max Loiacono
github_url: https://github.com/itsmaxymoo/quittit-website
personal_site_url: https://itsmaxymoo.com

# Defaults
defaults:
  # Post defaults
  -
    scope:
      path: ""
    values:
      layout: base

# Build settings
timezone: America/New_York
markdown: kramdown
sass:
  style: compressed

# Exclude from jekyll processing
exclude:
  - LICENSE.md
  - README.md
  - TODO.md
  - "*.sh"
  - .vscode/
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - CNAME
